### ISSUE TITLE
Hostname not being created automatically when task is FARGATE

### ISSUE THREAD

**Issue by FabioORamos** [DNXLabs/terraform-aws-ecs-app#20]
If we deploy FARGATE the `hostname_create: true` doesn't seem to have any effect

**Comment by lzrocha** [comment]
Hi @FabioORamos 
I couldn't reproduce the issue with module versions from 4.13.1 to 5.4.0. Please check if the `alb_only` is set true as required by the 'count' conditional.
https://github.com/DNXLabs/terraform-aws-ecs-app/blob/5.2.0/route53-record.tf#L8
Thanks!

**Comment by FabioORamos** [comment]
This issue has been fixed in the updated version.
